---
segment_anything_checkpoint_path: ~/sam_vit_b_01ec64.pth
image_resize: 1.0
topics:
    camera_info: /camera/color/camera_info
    rgb: /camera/color/image_raw
    depth: /camera/aligned_depth_to_color/image_raw
objects:
    - name: bbq_sauce
      scale: 0.1
      pose_topic: /dope/pose_BBQSauce
      model_path: meshes/hope/bbq_sauce/bbq_sauce.obj
    - name: orange_juice
      scale: 0.01
      pose_topic: /dope/pose_OrangeJuice
      model_path: meshes/hope/orange_juice/orange_juice.obj
    - name: mustard
      scale: 0.01
      pose_topic: /dope/pose_Mustard
      model_path: meshes/hope/mustard/mustard.obj
losses:
    l1_rgb_with_mask: true
    weight_rgb: 0.25
    l1_depth_with_mask: true
    weight_depth: 0.25
    l1_mask: true
    weight_mask: 0.5
hyperparameters:
    nb_iterations: 30
    batchsize: 8
    base_lr: 20
    learning_rates_bound: [0.01, 100]
    learning_rate_base: 1
    lr_decay: 0.1
render_images:
    nrow: 4
    final_width_batch: 2000
    add_background: true
    alpha_overlay: 0.7
    add_countour: true
    color_countour: [0.46, 0.73, 0]
    flip_result: true
    crop_around_mask: true
